from typing import Any


PROMPT_PROFILES: dict[str, dict[str, Any]] = {
    "balanced": {
        "style_base": "cinematic, coherent motion, high detail",
        "camera_default": "slow dolly in",
        "camera_closeup": "gentle close-up framing with minimal shake",
        "camera_drone": "slow aerial tracking shot",
        "scene_city": "urban outdoor environment",
        "scene_forest": "dense forest environment",
        "scene_interior": "interior environment with readable depth",
        "scene_default": "cinematic scene matching the prompt",
        "scene_suffix": "with stable composition and readable subject separation",
        "action_walk": "subject walks naturally with subtle body motion",
        "action_run": "subject runs forward with controlled motion blur",
        "action_default": "subject performs a clear, simple motion consistent with the prompt",
        "shot_plan": [
            {
                "beat": "establish subject and scene",
                "camera": "medium framing",
                "motion": "slow push in",
                "camera_path": "push-in",
                "camera_intensity": 0.45,
                "motion_strength": 0.4,
                "pose_hint_type": "pose-sparse",
                "pose_hint_strength": 0.35,
                "depth_hint_type": "depth-soft",
                "depth_hint_strength": 0.45,
                "transition_type": "cut",
                "transition_strength": 0.2,
                "duration_sec": 1.0,
                "emphasis": "clear subject readability",
            },
            {
                "beat": "continue primary action",
                "camera": "slightly closer framing",
                "motion": "steady forward movement",
                "camera_path": "forward-track",
                "camera_intensity": 0.5,
                "motion_strength": 0.5,
                "pose_hint_type": "pose-track",
                "pose_hint_strength": 0.5,
                "depth_hint_type": "depth-soft",
                "depth_hint_strength": 0.5,
                "transition_type": "match-cut",
                "transition_strength": 0.35,
                "duration_sec": 1.0,
                "emphasis": "coherent body motion",
            },
            {
                "beat": "land the shot with stable finish",
                "camera": "hero framing",
                "motion": "gentle settle",
                "camera_path": "settle",
                "camera_intensity": 0.3,
                "motion_strength": 0.3,
                "pose_hint_type": "pose-hold",
                "pose_hint_strength": 0.4,
                "depth_hint_type": "depth-focus-subject",
                "depth_hint_strength": 0.55,
                "transition_type": "ease-out",
                "transition_strength": 0.4,
                "duration_sec": 1.0,
                "emphasis": "clean ending frame",
            },
        ],
        "negative_prompt": "flicker, blurry, low detail, duplicate subject, distorted limbs",
    },
    "strict": {
        "style_base": "cinematic realism, stable framing, controlled lighting, high detail",
        "camera_default": "locked cinematic push-in",
        "camera_closeup": "stable close-up framing with minimal camera shake",
        "camera_drone": "smooth aerial glide with limited motion drift",
        "scene_city": "realistic urban environment with grounded perspective",
        "scene_forest": "realistic forest environment with stable depth cues",
        "scene_interior": "realistic interior environment with controlled depth and lighting",
        "scene_default": "grounded cinematic environment matching the prompt",
        "scene_suffix": "with stable geometry, consistent lighting, and clean subject edges",
        "action_walk": "subject walks steadily with controlled limb motion",
        "action_run": "subject runs with grounded posture and stable body silhouette",
        "action_default": "subject performs a restrained, readable motion with minimal distortion",
        "shot_plan": [
            {
                "beat": "stable establishing frame",
                "camera": "locked medium wide shot",
                "motion": "minimal camera movement",
                "camera_path": "locked",
                "camera_intensity": 0.2,
                "motion_strength": 0.25,
                "pose_hint_type": "pose-anchor",
                "pose_hint_strength": 0.45,
                "depth_hint_type": "depth-structured",
                "depth_hint_strength": 0.6,
                "transition_type": "hard-cut",
                "transition_strength": 0.15,
                "duration_sec": 1.2,
                "emphasis": "scene stability",
            },
            {
                "beat": "controlled subject motion",
                "camera": "measured push in",
                "motion": "steady tracking",
                "camera_path": "measured-push",
                "camera_intensity": 0.35,
                "motion_strength": 0.4,
                "pose_hint_type": "pose-locked-track",
                "pose_hint_strength": 0.6,
                "depth_hint_type": "depth-structured",
                "depth_hint_strength": 0.65,
                "transition_type": "dissolve-short",
                "transition_strength": 0.2,
                "duration_sec": 1.0,
                "emphasis": "anatomical consistency",
            },
            {
                "beat": "stable hero close",
                "camera": "clean hero frame",
                "motion": "gentle stop",
                "camera_path": "micro-settle",
                "camera_intensity": 0.2,
                "motion_strength": 0.25,
                "pose_hint_type": "pose-hold",
                "pose_hint_strength": 0.55,
                "depth_hint_type": "depth-focus-subject",
                "depth_hint_strength": 0.7,
                "transition_type": "ease-out",
                "transition_strength": 0.3,
                "duration_sec": 0.8,
                "emphasis": "crisp final composition",
            },
        ],
        "negative_prompt": "flicker, blur, unstable anatomy, warped face, duplicate subject, camera shake",
    },
    "creative": {
        "style_base": "stylized cinematic imagery, expressive lighting, bold texture, dynamic motion",
        "camera_default": "dynamic sweeping dolly move",
        "camera_closeup": "dramatic close-up with expressive perspective",
        "camera_drone": "wide aerial arc with energetic motion",
        "scene_city": "stylized city environment with neon atmosphere",
        "scene_forest": "stylized forest environment with dramatic depth and light shafts",
        "scene_interior": "stylized interior environment with theatrical lighting",
        "scene_default": "stylized cinematic environment matching the prompt",
        "scene_suffix": "with exaggerated atmosphere and strong visual contrast",
        "action_walk": "subject walks with expressive motion and dramatic pose rhythm",
        "action_run": "subject runs with energetic momentum and stylized movement trails",
        "action_default": "subject performs an expressive motion with cinematic dynamism",
        "shot_plan": [
            {
                "beat": "dramatic reveal",
                "camera": "wide dynamic frame",
                "motion": "sweeping lateral move",
                "camera_path": "wide-arc",
                "camera_intensity": 0.75,
                "motion_strength": 0.7,
                "pose_hint_type": "pose-expressive",
                "pose_hint_strength": 0.45,
                "depth_hint_type": "depth-atmospheric",
                "depth_hint_strength": 0.5,
                "transition_type": "whip-pan",
                "transition_strength": 0.6,
                "duration_sec": 0.9,
                "emphasis": "atmosphere and scale",
            },
            {
                "beat": "accent the action peak",
                "camera": "aggressive push in",
                "motion": "energetic forward sweep",
                "camera_path": "fast-push",
                "camera_intensity": 0.85,
                "motion_strength": 0.85,
                "pose_hint_type": "pose-dynamic",
                "pose_hint_strength": 0.6,
                "depth_hint_type": "depth-atmospheric",
                "depth_hint_strength": 0.45,
                "transition_type": "motion-blend",
                "transition_strength": 0.7,
                "duration_sec": 1.1,
                "emphasis": "motion energy",
            },
            {
                "beat": "stylized finishing accent",
                "camera": "close hero perspective",
                "motion": "arc to settle",
                "camera_path": "hero-arc",
                "camera_intensity": 0.65,
                "motion_strength": 0.6,
                "pose_hint_type": "pose-stylized-hold",
                "pose_hint_strength": 0.5,
                "depth_hint_type": "depth-focus-subject",
                "depth_hint_strength": 0.55,
                "transition_type": "flare-fade",
                "transition_strength": 0.65,
                "duration_sec": 1.0,
                "emphasis": "visual punch",
            },
        ],
        "negative_prompt": "muddy image, flat lighting, lifeless motion, duplicate subject, broken anatomy",
    },
}


def get_prompt_profile(name: str | None) -> tuple[str, dict[str, Any]]:
    profile_name = name or "balanced"
    if profile_name not in PROMPT_PROFILES:
        supported = ", ".join(sorted(PROMPT_PROFILES))
        raise ValueError(f"Unsupported prompt profile '{profile_name}'. Supported profiles: {supported}")
    return profile_name, PROMPT_PROFILES[profile_name].copy()
